/**
 * Type definitions for the lexicon
 *
 * These types are manually maintained based on the lexicon schema to avoid
 * JSR's restriction on global type augmentations. They match the types that
 * would be generated by @atcute/lex-cli.
 *
 * @module
 */

import { BlobRef } from "@atproto/api";
import { BookMetadata } from "@/libs/document";
import { BookFormat } from "@/types/book";

export namespace AtBook {
  export type MetaData = {
    $type?: "cc.readup.rbook#metadata";
    // Partial md5 hash of the book file, used as the unique identifier
    hash: string;
    format: BookFormat;
    title: string; 
    author: string;
    createdAt: number;
    updatedAt: number;
    // file size in bytes
    fileSize?: number;
    primaryLanguage?: string;
    sourceTitle?: string;
    metadata?: BookMetadata;
    metaHash?: string;
    progress?: [number, number]; 
  };

  export type ConfigData = {
    $type?: "cc.readup.rbook#metadata";
    name: string;
    author?: number;
    format?: string;
    identifier?: string;
    // ...
  };

  export type RBook = {
    $type: "cc.readup.rbook";
    name: string;
    createdAt: string;
    bookmeta: MetaData;
    coverblob?: BlobRef;
    docblob?: BlobRef;
    config?: BlobRef; 
    checksum?: string; // md5 hash
    attribution?: string;
  };
}

export namespace AtData {
  export type RLibrary = {
    $type: "cc.readup.library";
    name: string;
    createdAt: string;
    updatedAt: string;
    docblob?: BlobRef;
  };

  export type RSetting = {
    $type: "cc.readup.setting";
    name: string;
    createdAt: string;
    updatedAt: string;
    docblob?: BlobRef;
  };

  export type RFeed = {
    $type: "cc.readup.feed";
    name: string;
    createdAt: string;
    updatedAt: string;
    docblob?: BlobRef;
  };

  export type RUsage = {
    $type: "cc.readup.usage";
    name: string;
    createdAt: string;
    updatedAt: string;
    docblob?: BlobRef;
  };

  export type RStar = {
    $type: "cc.readup.star";
    name: string;
    createdAt: string;
    updatedAt: string;
    docblob?: BlobRef;
  };
}
