name: Release Desktop

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-desktop:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            args: --bundles appimage,deb,rpm
            apt-packages: >-
              libwebkit2gtk-4.1-dev libayatana-appindicator3-dev
              libgtk-3-dev libxdo-dev librsvg2-dev patchelf pkg-config
          - name: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            args: --bundles nsis,msi
          - name: macos-x64
            os: macos-11
            arch: x86_64
            target: x86_64-apple-darwin
          - name: macos-arm
            os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin
          
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.28.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.apt-packages }}

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm setup-vendors

      - name: Create Tauri env file
        run: |
          echo "NEXT_PUBLIC_APP_PLATFORM=tauri" > .env.local

      - name: Build and Release desktop app
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: tauri-apps/tauri-action@v1
        with:
          projectPath: .
          args: ${{ matrix.args }}
          tagName: Readup-v__VERSION__
          releaseName: 'Readup v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
